--- #YAML:1.0
name:                   Mail-File
version:                0.08
abstract:               Write mail messages to a plain text file.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Test::More:           0.47
  File::Basename:       0
  File::Path:           0
  File::Temp:           0
  Time::Piece:          0
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Meta:     0
build_requires:
  Test::More:           0.47

provides:
  Mail::File:
    file:     lib/Mail/File.pm
    version:  0.08
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
