--- #YAML:1.0
name:                     Mail-File
version:                  0.10
abstract:                 Write mail messages to a plain text file
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  File::Basename:         0
  File::Path:             0
  File::Temp:             0
  Time::Piece:            0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Mail::File:
    file:     lib/Mail/File.pm
    version:  0.10
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
